# config with a lot of errors to test error handling

empty = 

unexpected = "this key isnt in the schema"

boolean = HELLO

int = not a number
int2 = "not a number"
int3 = 123abc

float = not a number
double = not a number

string = bad string
string2 = "broken

# "
# above to close the string for IDE

badvec = hi
worsevec = ][
whatthehell = [["hi"]]

mixed = ["hello", 123, 4.56, true, "world"]

forgotquotes = [hello, world]

emptyvec = []

trailingcomma = [1, 2, 3,]

noclosing = [1, 2, 3

there isnt even an equal sign here


# not enough errors ? lol